### ISSUE TITLE
API keys commited to github for recyclarr

### ISSUE THREAD

**Issue by truxnell** [MasterMidi/nixos-config#1]
Hi :wave:,

I was browsing github as part of porting my homelab fro k8s to nixos, and I came across your nice setups in my searches.

I noticed that you have your sonarr/radarr API keys publically commited for recyclarr running which is something I always ensure are hidden for security
https://github.com/MasterMidi/nixos-config/blob/main/hosts/david/recyclarr/sonarr/default.nix
https://github.com/MasterMidi/nixos-config/blob/main/hosts/david/recyclarr/radarr/default.nix

On the off chance you aren't aware, you are able to use secrets in recyclarr as per below and load a secrets file in as a envfile, then reference the env var as `!env_var` in the recyclar config. :smile: 
https://recyclarr.dev/wiki/yaml/secrets-reference/

**Comment by MasterMidi** [comment]
Hey

I am aware of it and have been meaning to change to some sort of secret management. I'm going to take this as my wake up-call to finally do it 😅

But I appreciate you taking your time to let me know!
